version: 2

# Set build parameters
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Explicitly set Python requirements
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
