[tool.cibuildwheel.linux]
before-all = [
    "yum -y install gsl",
    "yum -y install gsl-devel"
]
[tool.cibuildwheel.macos]
before-all = [
    "brew install gsl",
    "brew install llvm",
    "brew install libomp"
]
[tool.cibuildwheel.windows]
before-all = [
    "vcpkg install gsl gsl:x64-windows"
]
